---
# tasks file for webserver

- name: Install Dependencies
  become: yes
  apt:
    update_cache: yes
    name:
      - python3
      - php-cgi
      - systemd
    state: present

- name: Copy Source Code
  become: yes
  copy:
    src: code/
    dest: /etc/crazycalculatorz/

- name: Copy systemd Service File
  become: yes
  copy:
    src: crazycalculatorz.service
    dest: /etc/systemd/system/crazycalculatorz.service
    mode: '0644'

- name: Enable and Start server.py service
  become: yes
  systemd:
    name: crazycalculatorz
    enabled: yes
    state: started
    daemon_reload: yes

