# Pull ubuntu image from dockerhub
FROM ubuntu:latest

# Avoid prompts
ENV DEBIAN_FRONTEND=noninteractive

# Update repos and install dependencies
RUN apt-get update && \
    apt-get install -y python3 php-cgi && \
    apt-get clean

# Create a dir on the container
WORKDIR /app

# Copy server files to container
COPY /code /app

# Change working dir to /app/src
WORKDIR /app/src

EXPOSE 80
CMD ["python3", "server.py", "0.0.0.0", "80"]
#CMD ["tail", "-f", "/dev/null"]

