version: '3'

services:
  webserv:
    build: ./webserv
    networks:
      proxynet:
        ipv4_address: 172.16.1.2

  rproxy:
    build: ./rproxy
    volumes:
      - ./rproxy/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 443:8443
    networks:
        proxynet:
          ipv4_address: 172.16.1.3


networks:
  proxynet:
    ipam:
      config:
        - subnet: 172.16.1.0/24
