version: '3'

services:
  webserv:
    build: ./webserv
    ports:
      - "80:80"
    networks:
      internal_corp:
        ipv4_address: 10.0.1.5

  rproxy:
    build: ./rproxy
    volumes:
      - ./rproxy/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 443:8443
    networks:
        internal_corp:
          ipv4_address: 10.0.1.10


networks:
  internal_corp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
